### ISSUE TITLE
Error: Problem with `mutate()` column `discurso`.

### ISSUE THREAD

**Issue by figueiraguilherme** [dcardosos/speechbr#2]
desig <- speechbr::speech_data( keyword = "desigualdade",  reference_date = "2021-12-01", qtd_days = 1095)

Erro: Problem with `mutate()` column `discurso`.
i `discurso = txt`.
i `discurso` must be size 987 or 1, not 1052.
Run `rlang::last_error()` to see where the error occurred.
Além disso: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by dcardosos** [comment]
Thank you for the warning.

The problem was solved, and amazingly, with a single line of code, `purrr::discard(nchar(.) <= 250)`, in the function that transforms the URL of the speeches. The problem was that the function finds all the "href" attributes in the HTML page, but sometimes the table has more than one "href" per line, per speech, so the vector of texts, which is sent to the `discurso` column, becomes greater than the number of rows in the table, and results in the error shown.

The commit of resolution is 0b1e39c63e88833c6549acf8fd95b5d7d31f1138.

Don't forget to install the package again to update it, with `devtools::install_github("dcardosos/speechbr")`.

Thank you
